CREATE TABLE IF NOT EXISTS PerfisADMs (
    idPerfis INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Status TINYINT NOT NULL DEFAULT 0,
    Senha VARCHAR(255) NOT NULL,
    Foto LONGBLOB NULL,
    Premium TINYINT NOT NULL DEFAULT 0,
    Cidade VARCHAR(120) DEFAULT NULL,
    Generos TEXT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS LivrosADMs (
    idLivrosADMs INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Autor VARCHAR(255) DEFAULT NULL,
    Editora VARCHAR(255) DEFAULT NULL,
    Ano INT DEFAULT NULL,
    Genero VARCHAR(255) NOT NULL,
    Estado VARCHAR(255) DEFAULT NULL,
    Observacoes TEXT DEFAULT NULL,
    IdDono INT NOT NULL,
    Status TINYINT NOT NULL DEFAULT 0,
    Fotolivro LONGBLOB NULL,
    CONSTRAINT fk_livros_dono
        FOREIGN KEY (IdDono) REFERENCES PerfisADMs(idPerfis)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS conversasADMs (
    idConversa INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id1 INT NOT NULL,
    id2 INT NOT NULL,
    conteudo TEXT NOT NULL,
    Statuscvs TINYINT DEFAULT 0,
    CONSTRAINT fk_conv_id1
        FOREIGN KEY (id1) REFERENCES PerfisADMs(idPerfis)
        ON DELETE CASCADE,
    CONSTRAINT fk_conv_id2
        FOREIGN KEY (id2) REFERENCES PerfisADMs(idPerfis)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ReadSwapADMs (
    codADM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Usuario VARCHAR(255) NOT NULL UNIQUE,
    Senha VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
