-- Migração correspondente ao esquema legado atualmente em produção.
ALTER TABLE PerfisADMs
    MODIFY COLUMN Nome VARCHAR(255) NOT NULL,
    MODIFY COLUMN Email VARCHAR(255) NOT NULL,
    MODIFY COLUMN Cidade VARCHAR(120) DEFAULT NULL,
    MODIFY COLUMN Generos TEXT DEFAULT NULL;

ALTER TABLE conversasADMs
    ADD COLUMN idConversa INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST,
    MODIFY COLUMN conteudo TEXT NOT NULL,
    MODIFY COLUMN Statuscvs TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN DataEnvio DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER Statuscvs;

CREATE TABLE IF NOT EXISTS SwapsADMs (
    idSwap INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUsuario INT NOT NULL,
    idLivro INT NOT NULL,
    Gostou TINYINT NOT NULL,
    DataAvaliacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_swap_usuario_livro (idUsuario, idLivro),
    CONSTRAINT fk_swap_usuario FOREIGN KEY (idUsuario) REFERENCES PerfisADMs(idPerfis) ON DELETE CASCADE,
    CONSTRAINT fk_swap_livro FOREIGN KEY (idLivro) REFERENCES LivrosADMs(idLivrosADMs) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
